export const homeData = [
  {
    id: 0,
    img: "/images/blender.jpg",
    subImg: "/images/blender.jpg",
    subImg2: "/images/blender.jpg",
    title: "blender",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 10,000",
    btnText: "Add to cart",
    color: "red",
  },
  {
    id: 1,
    img: "/images/fridge.jpg",
    subImg: "/images/washing-machine.jpg",
    subImg2: "/images/blender.jpg",
    title: "fridge",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 50,000",
    btnText: "Add to cart",
    color: "blue",
  },
  {
    id: 2,
    img: "/images/washing-machine.jpg",
    subImg: "/images/fridge.jpg",
    subImg2: "/images/blender.jpg",
    title: "washing-machine",
    category: "Health and beauty",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 50,000",
    btnText: "Add to cart",
    color: "red",
  },
  {
    id: 3,
    img: "/images/bed.jpg",
    subImg: "/images/washing-machine.jpg",
    subImg2: "/images/fridge.jpg",
    title: "bed",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 30,000",
    btnText: "Add to cart",
    color: "blue",
  },
  {
    id: 4,
    img: "/images/computer-accessories.jpg",
    subImg: "/images/washing-machine.jpg",
    subImg2: "/images/blender.jpg",
    title: "Fenty beauty lip care",
    category: "Phone and tablets",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 80,000",
    btnText: "Add to cart",
    color: "white",
  },
  {
    id: 5,
    img: "/images/shoes.jpg",
    subImg: "/images/washing-machine.jpg",
    subImg2: "/images/blender.jpg",
    title: "Fenty beauty lip care",
    category: "Phone and tablets",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 10,000",
    btnText: "Add to cart",
    color: "purple",
  },
  {
    id: 6,
    img: "/images/fan.jpg",
    subImg: "/images/shoes.jpg",
    subImg2: "/images/blender.jpg",
    title: "Fenty beauty lip care",
    category: "Health and beauty",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 50,000",
    btnText: "Add to cart",
    color: "purple",
  },
  {
    id: 7,
    img: "/images/clothes-two.jpg",
    title: "Fenty beauty lip care",
    category: "Phone and tablets",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 90,000",
    btnText: "Add to cart",
    color: "blue",
  },
  {
    id: 8,
    img: "/images/computer-accessories-two.jpg",
    title: "Fenty beauty lip care",
    category: "Phone and tablets",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 10,000",
    btnText: "Add to cart",
    color: "purple",
  },
  {
    id: 9,
    img: "/images/sofa-chair.jpg",
    title: "Fenty beauty lip care",
    category: "Health and beauty",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 100,000",
    btnText: "Add to cart",
    color: "red",
  },
  {
    id: 10,
    img: "/images/plates.jpg",
    title: "Fenty beauty lip care",
    category: "Health and beauty",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 50,000",
    btnText: "Add to cart",
    color: "whiter",
  },
  {
    id: 11,
    img: "/images/sneaker.jpg",
    title: "Fenty beauty lip care",
    category: "Electonics",
    detailDesc:
      "Lorem ipsum dolor sit amet consectetur. Quam interdum nulla id et in nisl urna mattis.",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 100,000",
    btnText: "Add to cart",
    color: "blue",
  },
];

export const dailyDeals = [
  {
    id: 0,
    img: "/images/computer-accessories.jpg",
    title: "Fenty beauty lip care",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 10,000",
    btnText: "Add to cart",
  },
  {
    id: 1,
    img: "/images/bed.jpg",
    title: "Fenty beauty lip care",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 10,000",
    btnText: "Add to cart",
  },
  {
    id: 2,
    img: "/images/clothes-two.jpg",
    title: "Fenty beauty lip care",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 10,000",
    btnText: "Add to cart",
  },
  {
    id: 3,
    img: "/images/fridge.jpg",
    title: "Fenty beauty lip care",
    desc: "Description should be this long",
    formerCost: "₦ 16,000",
    currentCost: "₦ 10,000",
    btnText: "Add to cart",
  },
];
export const categoriesData = [
  {
    id: 0,
    img: "/images/blender.jpg",
    desc: "Home appliances",
  },
  {
    id: 1,
    img: "/images/blender.jpg",
    desc: "Computer accessories",
  },
  {
    id: 2,
    img: "/images/blender.jpg",
    desc: "Clothes",
  },
  {
    id: 3,
    img: "/images/blender.jpg",
    desc: "Herbal health",
  },
  {
    id: 4,
    img: "/images/blender.jpg",
    desc: "Kitchen utensils",
  },
  {
    id: 5,
    img: "/images/blender.jpg",
    desc: "Ladies clothing",
  },
  {
    id: 6,
    img: "/images/blender.jpg",
    desc: "Men’s clothing",
  },
  {
    id: 7,
    img: "/images/blender.jpg",
    desc: "Jewelries and accessories",
  },
  {
    id: 8,
    img: "/images/blender.jpg",
    desc: "Bags",
  },
  {
    id: 9,
    img: "/images/blender.jpg",
    desc: "Food products",
  },
  {
    id: 10,
    img: "/images/blender.jpg",
    desc: "Designers",
  },
  {
    id: 11,
    img: "/images/blender.jpg",
    desc: "Clothes",
  },
];

export const ourShopCategories = [
  {
    id: 0,
    img: "/images/fan.jpg",
    desc: "Home appliances",
  },
  {
    id: 1,
    img: "/images/computer-accessories-two.jpg",
    desc: "Computer accessories",
  },
  {
    id: 2,
    img: "/images/clothes-two.jpg",
    desc: "Clothes",
  },
];
//  footerLinks

export const footerLinks = [
  {
    title: "Information",
    links: [
      { title: "About us", url: "/" },
      { title: "Terms and services", url: "/" },
      { title: "Pricing", url: "/" },
      { title: "Privacy policy", url: "/" },
    ],
  },
  {
    title: "My Account",
    links: [
      { title: "My orders", url: "/" },
      { title: "Ratings and review", url: "/" },
      { title: "Saved items", url: "/" },
      { title: "Recently viewed", url: "/" },
      { title: "Recently searched", url: "/" },
      { title: "Saved cards", url: "/" },
    ],
  },
  {
    title: "Help center",
    links: [
      { title: "Support@inshopper.com", url: "/" },
      { title: "Help center", url: "/" },
      { title: "Contact us", url: "/" },
      { title: "FAQS", url: "/" },
    ],
  },
];
